version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - zip -r src.zip .
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://src.zip
